# Generated by Django 2.0.1 on 2018-02-18 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='group',
            field=models.IntegerField(default=0),
        ),
    ]
