# Generated by Django 2.0.1 on 2018-02-22 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_log_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcomment',
            name='creator',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='groupcomment',
            name='creator',
            field=models.CharField(default='', max_length=50),
        ),
    ]
