# Generated by Django 2.0.1 on 2018-02-09 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.Group'),
        ),
    ]
