# Generated by Django 2.0.1 on 2018-02-09 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_document_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.Group'),
        ),
    ]
