# Generated by Django 2.0.1 on 2018-02-09 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20180209_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Group'),
        ),
    ]
