# Generated by Django 2.0.1 on 2018-02-10 15:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0009_auto_20180209_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='isLeader',
            field=models.ManyToManyField(related_name='isLeader', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL),
        ),
    ]
