# Generated by Django 2.0.1 on 2018-02-11 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20180210_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=500)),
                ('document', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Document')),
            ],
        ),
        migrations.CreateModel(
            name='GroupComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=500)),
                ('group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Group')),
            ],
        ),
    ]
