# Generated by Django 2.0.2 on 2018-02-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='creator',
            field=models.IntegerField(default=1),
        ),
    ]
