# Generated by Django 2.0.2 on 2018-02-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_group_modifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='modifier',
            field=models.IntegerField(default=1),
        ),
    ]
