# Generated by Django 2.0.2 on 2018-02-16 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_document_modifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
