# Generated by Django 2.0.1 on 2018-02-17 16:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0019_document_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcomment',
            name='hasRead',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupcomment',
            name='hasRead',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
