# Generated by Django 2.0.2 on 2018-02-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20180217_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='filehash',
            field=models.CharField(default='', max_length=200),
        ),
    ]
