# Generated by Django 2.0.1 on 2018-01-27 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0002_auto_20180127_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='date',
        ),
    ]
