# Generated by Django 2.0.1 on 2018-01-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0003_remove_folder_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
