# Generated by Django 2.0.1 on 2018-01-27 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0004_document_is_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='file_title',
            new_name='document_title',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='file_type',
            new_name='document_type',
        ),
    ]
